# NeuroCorgi SDK 🐕, CeCILL-C license
# Builds neurocorgi/neurocorgi_sdk:latest-n2d2 image on DockerHub https://hub.docker.com/r/neurocorgi/neurocorgi_sdk
# Image is CUDA-optimized for NeuroCorgi applications for single/multi-GPU training and inference with N2D2

# Use PyTorch image from nvcr.io/nvidia/pytorch:22.04-py3
FROM nvcr.io/nvidia/pytorch:22.04-py3

ARG DEBIAN_FRONTEND=noninteractive

# Install linux packages
RUN apt update \
    && apt install --no-install-recommends -y git tar zip curl htop screen libpython3-dev python3-pip gnuplot libopencv-dev

# Working directory to install n2d2
WORKDIR /opt

# Get N2D2 from Github
RUN git clone --recursive --depth 1 https://github.com/CEA-LIST/N2D2.git

# Install required Python libraries for N2D2
RUN pip install onnx onnxsim onnxruntime

# Compile N2D2 and install it in the Python libs
RUN cd N2D2 && pip install .

# Create working directory
WORKDIR /usr/src/neurocorgi_sdk

# Get NeuroCorgi SDK from Github
RUN git clone https://github.com/CEA-LIST/neurocorgi_sdk.git /usr/src/neurocorgi_sdk

# Install SDK and required libraries 
RUN python3 -m pip install --upgrade pip wheel
RUN pip install --no-cache .

# Because there will be a dynamic link issue with openmpi
# Run this command to fix it
# source: https://github.com/horovod/horovod/issues/2187
RUN echo 'ldconfig' >> /root/.bashrc


# Usage Examples -------------------------------------------------------------------------------------------------------

# Build and Push
# t=neurocorgi/neurocorgi_sdk:latest-n2d2 && sudo docker build -f docker/Dockerfile -t $t . && sudo docker push $t

# Pull and Run with access to all GPUs
# t=neurocorgi/neurocorgi_sdk:latest-n2d2 && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all $t

# Pull and Run with access to GPUs 2 and 3 (inside container CUDA devices will appear as 0 and 1)
# t=neurocorgi/neurocorgi_sdk:latest-n2d2 && sudo docker pull $t && sudo docker run -it --ipc=host --gpus '"device=2,3"' $t

# Pull and Run with local directory access (i.e., local volume mounted)
# t=neurocorgi/neurocorgi_sdk:latest-n2d2 && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all -v "$(pwd)"/datasets:/usr/src/datasets $t